version: "3.7"

services:

  samba:
    image: dperson/samba
    container_name: samba
    restart: always
    command: '-u "$SAMBA_USER;$SAMBA_PASSWORD" -s "media;/media;yes;no;no;agusgambina;agusgambina;agusgambina;agusgambina" -s "downloads;/downloads;yes;no;no;agusgambina;agusgambina;agusgambina"'
    stdin_open: true
    tty: true
    ports:
      - 139:139
      - 445:445
    volumes:
      - /usr/share/zoneinfo/America/Argentina/Buenos_Aires:/etc/localtime
      - $SAMBA_MEDIA:/media
      - $SAMBA_DOWNLOADS:/downloads