version: "3.7"

services:

  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=$PLEX_CLAIM
    volumes:
      - /home/$USER/storage/config/PlexMediaServer/config:/config
      - /home/$USER/storage/media/video:/movies
      - /media/driveone/storage/media:/media
    restart: always

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /home/$USER/storage/downloads/p2p/torrents/config:/config
      - /home/$USER/storage/downloads/p2p/torrents/incoming:/downloads
      - /home/$USER/storage/downloads/p2p/torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
