version: "3.7"

services:

  # ENV VARIABLES
  # PLEX_CONFIG="/home/$USER/storage/config/PlexMediaServer/config"
  # PLEX_VIDEO="/home/$USER/storage/media/video"
  # PLEX_MEDIA="/media/driveone/storage/media"
  plex:
    image: linuxserver/plex
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - UMASK_SET=022 #optional
      - PLEX_CLAIM=$PLEX_CLAIM
    volumes:
      - $PLEX_CONFIG:/config
      - $PLEX_VIDEO:/movies
      - $PLEX_MEDIA:/media
    restart: always