version: "3.7"

services:

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_HOME=/combustion-release/
      - USER=$TRANSMISION_USER
      - PASS=$TRANSMISION_PASS
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - $TRANSMISION_CONFIG:/config
      - $TRANSMISION_INCOMING:/downloads
      - $TRANSMISION_WATCH:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  amule:
    image: tchabaud/amule
    container_name: amule
    environment:
      - PUID=2000
      - PGID=2000
      - WEBUI_PWD=amule
      - WEBUI_TEMPLATE=AmuleWebUI-Reloaded
    volumes:
      - $AMULE_CONFIG:/home/amule/.aMule
      - $AMULE_TEMP:/temp
      - $AMULE_INCOMING:/incoming
    ports:
      - 4711:4711
      - 4662:4662
      - 4672:4672/udp
    restart: always

  flexget:
    image: wiserain/flexget
    container_name: flexget
    environment:
      - FG_WEBUI_PASSWD=$FLEXGET_PASS
      - FG_LOG_LEVEL=info
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
      - TORRENT_PLUGIN=transmission
      - FG_PLUGINS="Subliminal"
    volumes:
      - $FLEXGET_CONFIG:/config
      - $STORAGE:/data
    ports:
      - 3539:3539
    restart: unless-stopped
    links:
      - transmission
