version: "3.7"

services:

  transmission:
    image: linuxserver/transmission
    container_name: transmission
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Argentina/Buenos_Aires
    volumes:
      - /home/$USER/storage/downloads/p2p/torrents/config:/config
      - /home/$USER/storage/downloads/p2p/torrents/incoming:/downloads
      - /home/$USER/storage/downloads/p2p/torrents/watch:/watch
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped

  amule:
    image: tchabaud/amule
    container_name: amule
    environment:
      - PUID=2000
      - PGID=2000
      - WEBUI_PWD=amule
      - WEBUI_TEMPLATE=AmuleWebUI-Reloaded
    volumes:
      - /home/$USER/storage/downloads/p2p/amule/conf:/home/amule/.aMule
      - /home/$USER/storage/downloads/p2p/amule/temp:/temp
      - /home/$USER/storage/downloads/p2p/amule/incoming:/incoming
    ports:
      - 4711:4711
      - 4662:4662
      - 4672:4672/udp
    restart: always